spring:
  application:
    name: state-service
  zipkin:
    base-url: ${ZIPKIN-SERVER:http://localhost:9411}

server:
  port: ${PORT:8081}
  servlet:
    context-path: /state-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/