spring:
  application:
    name: STATE-SERVICE
  boot:
    admin:
      client:
        url: ${SPRING_ADMIN_URL:http://localhost:8888}

server:
  port: ${PORT:8081}
  servlet:
    context-path: /state-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'