spring:
  application:
    name: country-service

server:
  port: ${PORT:8080}
  servlet:
    context-path: /country-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/