spring:
  application:
    name: country-service
  zipkin:
    base-url: ${ZIPKIN-SERVER:http://localhost:9411}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /country-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/