server:
  port: ${PORT:9000}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: GATEWAY-SERVICE
  boot:
    admin:
      client:
        url: ${SPRING_ADMIN_URL:http://localhost:8888}
  cloud:
    gateway:
      routes:
        - id: countryservice
          uri: lb://COUNTRY-SERVICE
          predicates:
            - Path=/country-service/**
        - id: stateservice
          uri: lb://STATE-SERVICE
          predicates:
            - Path=/state-service/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
